default: &default
  adapter: postgresql
  encoding: unicode

development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: my_database_production
